# category_mapping.py

SITE_CATEGORIES = {
    "1337x": ["filesharing", "community"],
    "2Dimensions": ["design", "creative"],
    "3dnews": ["news"],
    "7Cups": ["community"],
    "8tracks": ["music", "streaming"],
    "9GAG": ["social", "community"],
    "APClips (NSFW)": ["NSFW", "streaming"],
    "About.me": ["social", "creative"],
    "Academia.edu": ["education"],
    "AdmireMe.Vip (NSFW)": ["NSFW", "social"],
    "Air Pilot Life": ["travel", "blogging"],
    "Airbit": ["music", "marketplace"],
    "Airliners": ["travel", "community"],
    "All Things Worn (NSFW)": ["NSFW", "marketplace"],
    "AllMyLinks": ["social"],
    "AniWorld": ["streaming", "community"],
    "Anilist": ["social", "community"],
    "Apple Developer": ["coding", "education"],
    "Apple Discussions": ["forum", "community"],
    "Archive of Our Own": ["blogging", "community"],
    "Archive.org": ["community", "filesharing"],
    "ArtStation": ["creative", "design"],
    "Asciinema": ["coding", "community"],
    "Ask Fedora": ["forum", "community"],
    "AskFM": ["social", "community"],
    "Atcoder": ["coding", "education"],
    "Audiojungle": ["music", "marketplace"],
    "Autofrage": ["forum", "community"],
    "Avizo": ["marketplace"],
    "BLIP.fm": ["music", "streaming"],
    "BOOTH": ["marketplace", "creative"],
    "Bandcamp": ["music", "marketplace"],
    "Bazar.cz": ["marketplace"],
    "Behance": ["creative", "design"],
    "Bezuzyteczna": ["social", "community"],
    "BiggerPockets": ["finance", "community"],
    "BioHacking": ["education", "community"],
    "BitBucket": ["coding", "community"],
    "Bitwarden Forum": ["forum", "community"],
    "Blipfoto": ["creative", "blogging"],
    "Blogger": ["blogging"],
    "BoardGameGeek": ["gaming", "community"],
    "BongaCams (NSFW)": ["NSFW", "streaming"],
    "Bookcrossing": ["community"],
    "BraveCommunity": ["forum", "community"],
    "BugCrowd": ["coding", "community"],
    "BuyMeACoffee": ["marketplace", "community"],
    "BuzzFeed": ["news", "community"],
    "CGTrader": ["marketplace", "design"],
    "CNET": ["news", "community"],
    "CSSBattle": ["coding", "gaming"],
    "CTAN": ["community", "filesharing"],
    "Caddy Community": ["forum", "community"],
    "Car Talk Community": ["forum", "community"],
    "Carbonmade": ["creative", "design"],
    "Career.habr": ["coding", "community"],
    "Championat": ["community"],
    "Chaos": ["community"],
    "Chatujme.cz": ["messaging", "community"],
    "ChaturBate (NSFW)": ["NSFW", "streaming"],
    "Chess": ["gaming", "strategy"],
    "Choice Community": ["forum", "community"],
    "Clapper": ["social", "streaming"],
    "CloudflareCommunity": ["forum", "community"],
    "Clozemaster": ["education", "language"],
    "Clubhouse": ["social", "messaging"],
    "Code Snippet Wiki": ["coding", "community"],
    "Codeberg": ["coding", "community"],
    "Codecademy": ["education", "coding"],
    "Codechef": ["coding", "education"],
    "Codeforces": ["coding", "education"],
    "Codepen": ["coding", "creative"],
    "Coders Rank": ["coding", "community"],
    "Coderwall": ["coding", "community"],
    "Codewars": ["coding", "gaming"],
    "Coinvote": ["finance", "community"],
    "ColourLovers": ["creative", "design"],
    "Contently": ["blogging", "creative"],
    "Coroflot": ["creative", "design"],
    "Cracked": ["news", "community"],
    "Crevado": ["creative", "design"],
    "Crowdin": ["coding", "community"],
    "Cryptomator Forum": ["forum", "community"],
    "Cults3D": ["creative", "marketplace"],
    "CyberDefenders": ["coding", "community"],
    "DEV Community": ["coding", "blogging"],
    "DMOJ": ["coding", "education"],
    "DailyMotion": ["streaming"],
    "Dealabs": ["marketplace", "community"],
    "DeviantART": ["creative", "design"],
    "Discogs": ["music", "marketplace"],
    "Discord": ["social", "messaging"],
    "Discuss.Elastic.co": ["forum", "community"],
    "Disqus": ["community"],
    "Docker Hub": ["coding", "community"],
    "Dribbble": ["creative", "design"],
    "Duolingo": ["education", "language"],
    "Eintracht Frankfurt Forum": ["forum", "community"],
    "Empretienda AR": ["marketplace"],
    "Envato Forum": ["forum", "community"],
    "Erome (NSFW)": ["NSFW", "streaming"],
    "Exposure": ["creative", "blogging"],
    "EyeEm": ["creative", "design"],
    "F3.cool": ["social", "community"],
    "Fameswap": ["marketplace", "social"],
    "Fandom": ["community", "gaming"],
    "Fanpop": ["social", "community"],
    "Finanzfrage": ["finance", "community"],
    "Fiverr": ["marketplace", "creative"],
    "Flickr": ["creative"],
    "Flightradar24": ["travel", "community"],
    "Flipboard": ["news", "community"],
    "Football": ["community"],
    "FortniteTracker": ["gaming"],
    "Forum Ophilia (NSFW)": ["NSFW", "forum"],
    "Fosstodon": ["social", "community"],
    "Freelance.habr": ["coding", "marketplace"],
    "Freelancer": ["marketplace", "coding"],
    "Freesound": ["music", "creative"],
    "GNOME VCS": ["coding", "community"],
    "GaiaOnline": ["social", "gaming"],
    "Gamespot": ["gaming", "news"],
    "GeeksforGeeks": ["coding", "education"],
    "Genius (Artists)": ["music", "creative"],
    "Genius (Users)": ["music", "community"],
    "Gesundheitsfrage": ["community"],
    "GetMyUni": ["education", "community"],
    "Giant Bomb": ["gaming", "community"],
    "Giphy": ["creative", "social"],
    "GitBook": ["coding", "community"],
    "GitHub": ["coding", "community"],
    "GitLab": ["coding", "community"],
    "Gitea": ["coding", "community"],
    "Gitee": ["coding", "community"],
    "GoodReads": ["community"],
    "Google Play": ["marketplace"],
    "Gradle": ["coding", "community"],
    "Grailed": ["marketplace"],
    "Gravatar": ["creative"],
    "Gumroad": ["marketplace", "creative"],
    "Gutefrage": ["forum", "community"],
    "HackTheBox": ["coding", "gaming"],
    "Hackaday": ["coding", "community"],
    "HackenProof (Hackers)": ["coding", "community"],
    "HackerEarth": ["coding", "education"],
    "HackerNews": ["news", "community"],
    "HackerOne": ["coding", "community"],
    "HackerRank": ["coding", "education"],
    "Harvard Scholar": ["education", "community"],
    "Hashnode": ["coding", "blogging"],
    "Heavy-R (NSFW)": ["NSFW", "streaming"],
    "Holopin": ["coding", "community"],
    "Houzz": ["design", "marketplace"],
    "HubPages": ["blogging", "community"],
    "Hubski": ["social", "community"],
    "HudsonRock": ["community"],
    "IFTTT": ["community"],
    "IRC-Galleria": ["messaging", "social"],
    "Icons8 Community": ["creative", "design"],
    "Image Fap (NSFW)": ["NSFW", "streaming"],
    "ImgUp.cz": ["filesharing", "community"],
    "Imgur": ["social", "creative"],
    "Instagram": ["social", "creative"],
    "Instructables": ["education", "creative"],
    "Intigriti": ["coding", "community"],
    "Ionic Forum": ["forum", "community"],
    "Issuu": ["blogging", "creative"],
    "Itch.io": ["gaming", "marketplace"],
    "Itemfix": ["streaming", "community"],
    "Jellyfin Weblate": ["coding", "community"],
    "Jimdo": ["blogging", "creative"],
    "Joplin Forum": ["forum", "community"],
    "KEAKR": ["music", "social"],
    "Kaggle": ["coding", "education"],
    "Keybase": ["messaging", "community"],
    "Kick": ["streaming", "gaming"],
    "Kik": ["messaging", "social"],
    "Kongregate": ["gaming", "community"],
    "LOR": ["forum", "coding"],
    "Launchpad": ["coding", "community"],
    "LeetCode": ["coding", "education"],
    "LessWrong": ["blogging", "community"],
    "Letterboxd": ["blogging", "community"],
    "LibraryThing": ["community"],
    "Lichess": ["gaming", "strategy"],
    "LinkedIn": ["social"],
    "Linktree": ["social"],
    "Listed": ["blogging"],
    "LiveJournal": ["blogging", "community"],
    "Lobsters": ["coding", "community"],
    "LottieFiles": ["creative", "design"],
    "LushStories (NSFW)": ["NSFW", "blogging"],
    "MMORPG Forum": ["gaming", "forum"],
    "Mapify": ["travel", "community"],
    "Medium": ["blogging", "community"],
    "Memrise": ["education", "language"],
    "Minecraft": ["gaming"],
    "MixCloud": ["music", "streaming"],
    "Monkeytype": ["gaming", "education"],
    "Motherless (NSFW)": ["NSFW", "streaming"],
    "Motorradfrage": ["forum", "travel"],
    "MyAnimeList": ["social", "community"],
    "MyMiniFactory": ["creative", "marketplace"],
    "Mydramalist": ["social", "community"],
    "Myspace": ["social", "music"],
    "NICommunityForum": ["forum", "community"],
    "NationStates Nation": ["gaming", "community"],
    "NationStates Region": ["gaming", "community"],
    "Naver": ["news", "community"],
    "Needrom": ["filesharing"],
    "Newgrounds": ["social", "creative"],
    "Nextcloud Forum": ["forum", "community"],
    "Nightbot": ["community", "streaming"],
    "Ninja Kiwi": ["gaming", "community"],
    "NintendoLife": ["gaming", "news"],
    "NitroType": ["gaming", "community"],
    "NotABug.org": ["coding", "community"],
    "Nyaa.si": ["filesharing", "community"],
    "OGUsers": ["forum", "community"],
    "OpenStreetMap": ["community", "travel"],
    "Opensource": ["coding", "community"],
    "OurDJTalk": ["music", "forum", "community"],
    "PCGamer": ["gaming", "news"],
    "PSNProfiles.com": ["gaming", "community"],
    "Packagist": ["coding", "community"],
    "Pastebin": ["coding", "filesharing"],
    "Patreon": ["creative", "marketplace"],
    "PentesterLab": ["coding", "education"],
    "PepperIT": ["community"],
    "Periscope": ["streaming", "social"],
    "Pinkbike": ["forum", "community"],
    "PlayStore": ["marketplace"],
    "PocketStars (NSFW)": ["NSFW", "marketplace"],
    "Pokemon Showdown": ["gaming"],
    "Polarsteps": ["travel", "social"],
    "Polygon": ["gaming", "news"],
    "Polymart": ["marketplace", "coding"],
    "Pornhub (NSFW)": ["NSFW", "streaming"],
    "ProductHunt": ["social", "community"],
    "PromoDJ": ["music", "community"],
    "PyPi": ["coding", "filesharing"],
    "Rajce.net": ["creative", "community"],
    "Rarible": ["marketplace", "creative"],
    "Rate Your Music": ["music", "community"],
    "Rclone Forum": ["forum", "community"],
    "RedTube (NSFW)": ["NSFW", "streaming"],
    "Redbubble": ["creative", "marketplace"],
    "Reddit": ["social", "community"],
    "Reisefrage": ["travel", "community"],
    "Replit.com": ["coding", "education"],
    "ResearchGate": ["education", "community"],
    "ReverbNation": ["music", "social"],
    "Roblox": ["gaming", "community"],
    "RocketTube (NSFW)": ["NSFW", "streaming"],
    "RoyalCams": ["NSFW", "streaming"],
    "RubyGems": ["coding", "filesharing"],
    "Rumble": ["streaming", "social"],
    "RuneScape": ["gaming", "community"],
    "SWAPD": ["marketplace", "social"],
    "Sbazar.cz": ["marketplace"],
    "Scratch": ["coding", "education"],
    "Scribd": ["filesharing", "community"],
    "ShitpostBot5000": ["creative", "social"],
    "Shpock": ["marketplace"],
    "Signal": ["messaging", "social"],
    "Sketchfab": ["creative", "marketplace"],
    "Slack": ["messaging", "community"],
    "Slant": ["community"],
    "Slashdot": ["news", "community"],
    "SlideShare": ["education", "community"],
    "Slides": ["creative", "education"],
    "SmugMug": ["creative", "design"],
    "Smule": ["music", "social"],
    "Snapchat": ["messaging", "social"],
    "SoundCloud": ["music", "streaming"],
    "SourceForge": ["coding", "filesharing"],
    "SoylentNews": ["news", "community"],
    "Speedrun.com": ["gaming", "community"],
    "Spells8": ["education", "community"],
    "Splice": ["music", "creative"],
    "Splits.io": ["gaming", "community"],
    "Sporcle": ["gaming", "education"],
    "Sportlerfrage": ["community"],
    "SportsRU": ["community"],
    "Spotify": ["music", "streaming"],
    "Star Citizen": ["gaming", "community"],
    "Steam Community (Group)": ["gaming", "community"],
    "Steam Community (User)": ["gaming", "community"],
    "Strava": ["community"],
    "SublimeForum": ["forum", "community"],
    "TETR.IO": ["gaming", "community"],
    "TLDR Legal": ["community"],
    "TRAKTRAIN": ["music", "marketplace"],
    "Telegram": ["messaging", "social"],
    "Tellonym.me": ["messaging", "social"],
    "Tenor": ["creative", "social"],
    "ThemeForest": ["marketplace", "design"],
    "Tiendanube": ["marketplace"],
    "TnAFlix (NSFW)": ["NSFW", "streaming"],
    "Topcoder": ["coding", "gaming"],
    "TorrentGalaxy": ["filesharing", "community"],
    "TradingView": ["finance", "community"],
    "Trakt": ["streaming", "community"],
    "TrashboxRU": ["community"],
    "Trawelling": ["travel", "community"],
    "Trello": ["community"],
    "TryHackMe": ["coding", "education"],
    "Tuna": ["music", "streaming"],
    "Tweakers": ["community"],
    "Twitch": ["gaming", "streaming"],
    "Twitter": ["social"],
    "Typeracer": ["gaming", "education"],
    "Ultimate-Guitar": ["music", "community"],
    "Unsplash": ["creative", "design"],
    "Untappd": ["social", "community"],
    "VK": ["social"],
    "VLR": ["gaming", "community"],
    "VSCO": ["creative", "social"],
    "Velog": ["blogging", "coding"],
    "Velomania": ["community", "travel"],
    "Venmo": ["finance"],
    "Vero": ["social"],
    "Vimeo": ["streaming", "creative"],
    "VirusTotal": ["community"],
    "WICG Forum": ["forum", "community"],
    "Warrior Forum": ["forum", "community"],
    "Wattpad": ["blogging", "community"],
    "WebNode": ["blogging", "creative"],
    "Weblate": ["coding", "community"],
    "Weebly": ["blogging", "creative"],
    "Wikidot": ["community"],
    "Wikipedia": ["community"],
    "Windy": ["community"],
    "Wix": ["blogging", "creative"],
    "WolframalphaForum": ["forum", "community"],
    "WordPress": ["blogging", "creative"],
    "WordPressOrg": ["blogging", "community"],
    "Wordnik": ["language", "community"],
    "Wykop": ["social", "community"],
    "Xbox Gamertag": ["gaming"],
    "Xvideos (NSFW)": ["NSFW", "streaming"],
    "YandexMusic": ["music", "streaming"],
    "YouNow": ["streaming", "social"],
    "YouPic": ["creative", "community"],
    "YouPorn (NSFW)": ["NSFW", "streaming"],
    "YouTube": ["streaming", "social"],
    "akniga": ["filesharing", "community"],
    "authorSTREAM": ["creative", "community"],
    "babyRU": ["community"],
    "babyblogRU": ["blogging", "community"],
    "chaos.social": ["social", "community"],
    "couchsurfing": ["travel", "community"],
    "d3RU": ["community"],
    "dailykos": ["news", "community"],
    "datingRU": ["social"],
    "devRant": ["coding", "social"],
    "drive2": ["community"],
    "eGPU": ["community"],
    "eintracht": ["community"],
    "exophase": ["gaming", "community"],
    "fixya": ["community"],
    "fl": ["marketplace"],
    "forum_guns": ["forum"],
    "freecodecamp": ["coding", "education"],
    "furaffinity": ["community", "creative"],
    "geocaching": ["travel", "community"],
    "gfycat": ["streaming", "creative"],
    "habr": ["coding", "news"],
    "hackster": ["coding", "community"],
    "hunting": ["community"],
    "iMGSRC.RU": ["filesharing"],
    "igromania": ["gaming", "news"],
    "interpals": ["language", "social"],
    "irecommend": ["community"],
    "jbzd.com.pl": ["social", "community"],
    "jeuxvideo": ["gaming", "news"],
    "kaskus": ["forum", "community"],
    "kofi": ["creative", "marketplace"],
    "kwork": ["marketplace", "creative"],
    "last.fm": ["music", "social"],
    "leasehackr": ["finance", "community"],
    "livelib": ["community"],
    "mastodon.cloud": ["social", "community"],
    "mastodon.social": ["social", "community"],
    "mastodon.technology": ["social", "community"],
    "mastodon.xyz": ["social", "community"],
    "mercadolivre": ["marketplace"],
    "minds": ["social", "community"],
    "moikrug": ["coding", "community"],
    "mstdn.io": ["social", "community"],
    "nairaland.com": ["forum", "community"],
    "nnRU": ["community"],
    "note": ["blogging"],
    "npm": ["coding", "filesharing"],
    "opennet": ["coding", "news"],
    "osu!": ["gaming", "community"],
    "phpRU": ["coding", "community"],
    "pikabu": ["social", "community"],
    "pr0gramm": ["social", "community"],
    "prog.hu": ["coding", "forum"],
    "queer.af": ["social", "community"],
    "satsisRU": ["community"],
    "sessionize": ["community"],
    "skyrock": ["social", "blogging"],
    "social.tchncs.de": ["social", "community"],
    "spletnik": ["social", "community"],
    "svidbook": ["social", "community"],
    "threads": ["social"],
    "toster": ["coding", "community"],
    "uid": ["community"],
    "wiki.vg": ["coding", "community"],
    "xHamster (NSFW)": ["NSFW", "streaming"],
    "znanylekarz.pl": ["community"],
}

DEFAULT_CATEGORIES = ["unknown"]
